version: "3"
services:
  backend:
    container_name: backend
    build: .
    image: backend
    environment:
      - MYSQL_DATABASE=coolcream
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=Coolcream044752
    volumes:
      - ~/backend_data:/public/icecream-images

networks:
  default:
    external:
      name: allnetwork
